version: '3.8'
services:
  frontend:
    ports:
      - "3000:3000"
    restart: always
    image: harbor.stageogip.ru/4d-innopolis/frontend:$BUILD_BUILDID
    container_name: 4d_frontend
networks:
  default:
    external:
      name: 4d_network