export const SERVER_INIT = "SERVER_INIT";
export const DOWNLOAD_FILE = "DOWNLOAD_FILE";

export const GET_PARKING_GEO = "GET_PARKING_GEO";
export const GET_PARKING_PLACES = "GET_PARKING_PLACES";

export const UPDATE_TICKET = "UPDATE_TICKET";
export const GET_USER_TICKET = "GET_USER_TICKET";
export const GET_USER_TICKETS = "GET_USER_TICKETS";
export const GET_USER_TICKETS_LIVING = "GET_USER_TICKETS_LIVING";
export const GET_USER_TICKETS_PARKING = "GET_USER_TICKETS_PARKING";
export const GET_USER_TICKETS_WAREHOUSE = "GET_USER_TICKETS_WAREHOUSE";

export const GET_APARTMENTS = "GET_APARTMENTS";
export const GET_IDEAS_GEO = "GET_IDEAS_GEO";
export const GET_APARTMENTS_GEO = "GET_APARTMENTS_GEO";
export const GET_COMMERCE_GEO = "GET_COMMERCE_GEO";

export const GET_COMMERCE_PLACE = "GET_COMMERCE_PLACE";

export const GET_USER_PARKING_BUILDINGS = "GET_USER_PARKING_BUILDINGS";
export const GET_USER_PARKING_PLACES = "GET_USER_PARKING_PLACES";
export const GET_EMPLOYEE_TICKETS_LIVING = "GET_EMPLOYEE_TICKETS_LIVING";
export const REJECT_TICKET_LIVING = "REJECT_TICKET_LIVING";
export const APPROVE_TICKET_LIVING = "APPROVE_TICKET_LIVING";
export const GET_EMPLOYEE_TICKETS_PARKING = "GET_EMPLOYEE_TICKETS_PARKING";
export const REJECT_TICKET_PARKING = "REJECT_TICKET_PARKING";
export const APPROVE_TICKET_PARKING = "APPROVE_TICKET_PARKING";
export const SEND_CONTRACT_INFO_LIVING = "SEND_CONTRACT_INFO_LIVING";
export const GET_USER_TICKET_PARKING_PAYMENT_LINK = "GET_USER_TICKET_PARKING_PAYMENT_LINK";
export const UPDATE_TICKET_APARTMENT = "UPDATE_TICKET_APARTMENT";
export const UPDATE_TICKET_APARTMENT_VIEWED = "UPDATE_TICKET_APARTMENT_VIEWED";
export const SEND_CONTRACT_INFO_PARKING = "SEND_CONTRACT_INFO_PARKING";
export const GET_EMPLOYEE_TICKETS_WAREHOUSE = "GET_EMPLOYEE_TICKETS_WAREHOUSE";
export const REJECT_TICKET_WAREHOUSE = "REJECT_TICKET_WAREHOUSE";
export const APPROVE_TICKET_WAREHOUSE = "APPROVE_TICKET_WAREHOUSE";
export const SEND_CONTRACT_INFO_WAREHOUSE = "SEND_CONTRACT_INFO_WAREHOUSE";
export const GET_WAREHOUSE_PAYMENT_LINK = "GET_WAREHOUSE_PAYMENT_LINK";

export const DELETE_USER_TICKET = "DELETE_USER_TICKET";
export const DELETE_USER_TICKET_LIVING = "DELETE_USER_TICKET_LIVING";
export const DELETE_USER_TICKET_PARKING = "DELETE_USER_TICKET_PARKING";
export const DELETE_USER_TICKET_WAREHOUSE = "DELETE_USER_TICKET_WAREHOUSE";

export const CREATE_USER_TICKET = "CREATE_USER_TICKET";
export const CREATE_USER_TICKET_LIVING = "CREATE_USER_TICKET_LIVING";
export const CREATE_LEGAL_TICKET_LIVING = "CREATE_LEGAL_TICKET_LIVING";
export const CREATE_USER_TICKET_PARKING = "CREATE_USER_TICKET_PARKING";
export const CREATE_USER_TICKET_WAREHOUSE = "CREATE_USER_TICKET_WAREHOUSE";

export const ADD_USER_TICKET_FILE = "ADD_USER_TICKET_FILE";
export const ADD_USER_TICKET_FILE_LIVING = "ADD_USER_TICKET_FILE_LIVING";
export const ADD_USER_TICKET_NEIGHBOR = "ADD_USER_TICKET_NEIGHBOR";
export const REQUEST_APPROVAL_LIVING = "REQUEST_APPROVAL_LIVING";
export const ADD_USER_TICKET_FILE_PARKING = "ADD_USER_TICKET_FILE_PARKING";
export const ADD_USER_TICKET_FILE_WAREHOUSE = "ADD_USER_TICKET_FILE_WAREHOUSE";
export const ADD_WAREHOUSE_FILES = "ADD_WAREHOUSE_FILES";
export const ADD_PARKING_FILES = "ADD_PARKING_FILES";

export const GET_COMPANY_COMMERCE_TICKET = "GET_COMPANY_COMMERCE_TICKET";
export const GET_COMPANY_COMMERCE_TICKETS = "GET_COMPANY_COMMERCE_TICKETS";
export const GET_EMPLOYEE_COMMERCE_TICKET = "GET_EMPLOYEE_COMMERCE_TICKET";
export const GET_EMPLOYEE_COMMERCE_TICKETS = "GET_EMPLOYEE_COMMERCE_TICKETS";
export const CREATE_COMMERCE_TICKET = "CREATE_COMMERCE_TICKET";
export const ADD_COMMERCE_TICKET_FILE = "ADD_COMMERCE_TICKET_FILE";
export const REQUEST_APPROVAL_COMMERCE = "REQUEST_APPROVAL_COMMERCE";
export const APPROVE_TICKET_COMMERCE = "APPROVE_TICKET_COMMERCE";
export const REJECT_TICKET_COMMERCE = "REJECT_TICKET_COMMERCE";
export const CANCEL_TICKET_COMMERCE = "CANCEL_TICKET_COMMERCE";
export const DELETE_TICKET_COMMERCE = "DELETE_TICKET_COMMERCE";
export const SIGN_CONTRACT_COMMERCE = "SIGN_CONTRACT_COMMERCE";

export const REGISTER_EMPLOYEE = "REGISTER_EMPLOYEE";
export const ACCOUNT_BLOCK = "ACCOUNT_BLOCK";
export const ACCOUNT_UNBLOCK = "ACCOUNT_UNBLOCK";
export const ACCOUNT_SET_ROLES = "ACCOUNT_SET_ROLES";
export const ACCOUNT_LOGOUT = "ACCOUNT_LOGOUT";
export const USER_LOGIN = "USER_LOGIN";
export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const ACCOUNT_CREATE = "ACCOUNT_CREATE";
export const GET_ACCOUNT = "GET_ACCOUNT";
export const ACCESS_TOKEN_COOKIE = "access_token";
export const REFRESH_ACCESS_TOKEN_COOKIE = "refresh_token";
export const GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN";
export const SET_OAUTH_TOKENS = "SET_OAUTH_TOKENS";
export const FETCH_ACCESS_TOKEN = "FETCH_ACCESS_TOKEN";
export const CREATE_USER_VEHICLE = "CREATE_USER_VEHICLE";
export const UPDATE_USER_VEHICLE = "UPDATE_USER_VEHICLE";
export const STORE_USER_VEHICLES = "STORE_USER_VEHICLES";
export const CREATE_VEHICLE_DOCUMENT = "CREATE_VEHICLE_DOCUMENT";
export const DELETE_VEHICLE_DOCUMENT = "DELETE_VEHICLE_DOCUMENT";
export const UPDATE_VEHICLE_DOCUMENTS = "UPDATE_VEHICLE_DOCUMENTS";
export const DELETE_USER_VEHICLE = "DELETE_USER_VEHICLE";
export const CREATE_USER_NEIGHBOR = "CREATE_USER_NEIGHBOR";
export const UPDATE_USER_NEIGHBOR = "UPDATE_USER_NEIGHBOR";
export const DELETE_USER_NEIGHBOR = "DELETE_USER_NEIGHBOR";
export const CREATE_NEIGHBOR_DOCUMENT = "CREATE_NEIGHBOR_DOCUMENT";
export const DELETE_NEIGHBOR_DOCUMENT = "DELETE_NEIGHBOR_DOCUMENT";
export const UPDATE_NEIGHBOR_DOCUMENTS = "UPDATE_NEIGHBOR_DOCUMENTS";
export const STORE_USER_NEIGHBORS = "STORE_USER_NEIGHBORS";
export const CREATE_USER_DOCUMENT = "CREATE_USER_DOCUMENT";
export const DELETE_USER_DOCUMENT = "DELETE_USER_DOCUMENT";
export const GET_USER_DOCUMENTS = "GET_USER_DOCUMENTS";
export const STORE_USER_DOCUMENTS = "STORE_USER_DOCUMENTS";
export const UPDATE_USER_DOCUMENTS = "UPDATE_USER_DOCUMENTS";
export const GET_REFERENCES = "GET_REFERENCES";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const GET_USER_PROFILE_DEFAULT = "GET_USER_PROFILE_DEFAULT";
export const CHANGE_USER_PROFILE_PASSWORD = "CHANGE_USER_PROFILE_PASSWORD";
export const CHANGE_USER_PROFILE_EMAIL = "CHANGE_USER_PROFILE_EMAIL";
export const UPDATE_USER_PROFILE_AVATAR = "UPDATE_USER_PROFILE_AVATAR";

export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

export const GET_COMPANY = "GET_COMPANY";
export const UPDATE_COMPANY_PROFILE = "UPDATE_COMPANY_PROFILE";
export const UPDATE_COMPANY_LOGO = "UPDATE_COMPANY_LOGO";
export const UPDATE_COMPANY_CARD = "UPDATE_COMPANY_CARD";
export const UPDATE_COMPANY_BANK = "UPDATE_COMPANY_BANK";
export const SEND_VERIFY_COMPANY_REQUEST = "SEND_VERIFY_COMPANY_REQUEST";

export const GET_DESIGN_SECTIONS = "GET_DESIGN_SECTIONS";
export const GET_DESIGN_SECTION = "GET_DESIGN_SECTION";

export const GET_DATA = "GET_DATA";
export const UPDATE_LIKE = "UPDATE_LIKE";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const UPDATE_VOTE = "UPDATE_VOTE";
export const DELETE_ITEM = "DELETE_ITEM";
export const GET_DETAILS = "GET_DETAILS";
export const UPDATE_DETAILS = "UPDATE_DETAILS";
export const GET_PAYMENT_LINK = "GET_PAYMENT_LINK";

export const GET_VACANCY_REFERENCES = "GET_VACANCY_REFERENCES";

export const GET_USER_VACANCY = "GET_USER_VACANCY";
export const FETCH_USER_VACANCY_BY_ID = "FETCH_USER_VACANCY_BY_ID";
export const FETCH_VACANCY_RESPONDS_FOR_COMPANY = "FETCH_VACANCY_RESPONDS_FOR_COMPANY";
export const VIEW_RESPOND_AND_RELOAD_CANDIDATE = "VIEW_RESPOND_AND_RELOAD_CANDIDATE";

export const REJECT_AND_RELOAD_VACANCY_CANDIDATE = "REJECT_AND_RELOAD_VACANCY_CANDIDATE";
export const INVITE_AND_RELOAD_VACANCY_CANDIDATE = "INVITE_AND_RELOAD_VACANCY_CANDIDATE";
export const CANDIDATE_INTERVIEW_PASSED_AND_RELOAD = "CANDIDATE_INTERVIEW_PASSED_AND_RELOAD";
export const SEND_CANDIDATE_JOB_OFFER_AND_RELOAD = "SEND_CANDIDATE_JOB_OFFER_AND_RELOAD";
export const FETCH_EMPLOYEE_RESPONDS = "FETCH_EMPLOYEE_RESPONDS";
export const SEND_COMPANY_RESPOND_NOTIFICATION = "SEND_COMPANY_RESPOND_NOTIFICATION";
export const EXPORT_RESPONDS = "EXPORT_RESPONDS";

export const CREATE_VACANCY = "CREATE_VACANCY";
export const UPDATE_VACANCY = "UPDATE_VACANCY";
export const CLOSE_VACANCY = "CLOSE_VACANCY";
export const PUBLISH_VACANCY = "PUBLISH_VACANCY";
export const REJECT_VACANCY = "REJECT_VACANCY";
export const EXPORT_USER_VACANCIES = "EXPORT_USER_VACANCIES";

export const SEARCH_VACANCY = "SEARCH_VACANCY";
export const FETCH_VACANCY = "FETCH_VACANCY";
export const RESPOND_VACANCY = "RESPOND_VACANCY";

export const REJECT_VACANCY_CANDIDATE = "REJECT_VACANCY_CANDIDATE";
export const INVITE_VACANCY_CANDIDATE = "INVITE_VACANCY_CANDIDATE";
export const CANDIDATE_INTERVIEW_PASSED = "CANDIDATE_INTERVIEW_PASSED";
export const SEND_CANDIDATE_JOB_OFFER = "SEND_CANDIDATE_JOB_OFFER";
export const GET_RESPOND = "GET_RESPOND";

export const CREATE_IDEA = "CREATE_IDEA";
export const GET_CURRENT = "GET_CURRENT";

export const GET_USER_TICKETS_CROWDFUNDING = "GET_USER_TICKETS_CROWDFUNDING";
export const GET_EMPLOYEE_TICKETS_CROWDFUNDING = "GET_EMPLOYEE_TICKETS_CROWDFUNDING";
export const REJECT_TICKET_CROWDFUNDING = "REJECT_TICKET_CROWDFUNDING";
export const APPROVE_TICKET_CROWDFUNDING = "APPROVE_TICKET_CROWDFUNDING";
export const DELETE_USER_TICKET_CROWDFUNDING = "DELETE_USER_TICKET_CROWDFUNDING";
export const CREATE_USER_TICKET_CROWDFUNDING = "CREATE_USER_TICKET_CROWDFUNDING";
export const ADD_USER_TICKET_CROWDFUNDING_COVER = "ADD_USER_TICKET_CROWDFUNDING_COVER";
export const ADD_USER_TICKET_CROWDFUNDING_FILES = "ADD_USER_TICKET_CROWDFUNDING_FILES";

export const FETCH_VERIFICATION_REQUESTS = "FETCH_VERIFICATION_REQUESTS";
export const REJECT_VERIFICATION_REQUEST = "REJECT_VERIFICATION_REQUEST";
export const APPROVE_VERIFICATION_REQUEST = "APPROVE_VERIFICATION_REQUEST";
export const FETCH_VERIFICATION_REQUESTS_REFERENCES = "FETCH_VERIFICATION_REQUESTS_REFERENCES";

export const FETCH_TOURISM_MENU = "FETCH_TOURISM_MENU";
export const FETCH_LAYER_GEOJSON = "FETCH_LAYER_GEOJSON";
export const PUT_LAYER_GEOJSON = "PUT_LAYER_GEOJSON";
export const FETCH_TOURISM_ENTITY = "FETCH_TOURISM_ENTITY";

export const SET_ACTIVE_TOURISM_FEATURE = "SET_ACTIVE_TOURISM_FEATURE";
export const REMOVE_ACTIVE_TOURISM_FEATURE = "REMOVE_ACTIVE_TOURISM_FEATURE";

export const FETCH_LAYER_ROUTES = "FETCH_LAYER_ROUTES";
export const FETCH_LAYER_PLACES = "FETCH_LAYER_PLACES";

export const FETCH_TOURISM_PLACE = "FETCH_TOURISM_PLACE";
export const FETCH_TOURISM_ROUTE = "FETCH_TOURISM_ROUTE";
export const OFFER_TOURISM_ROUTE = "OFFER_TOURISM_ROUTE";
