export const SERVER_INIT = "SERVER_INIT";

export const GET_PARKING_GEO = "GET_PARKING_GEO";
export const GET_PARKING_PLACES = "GET_PARKING_PLACES";

export const GET_USER_TICKET = "GET_USER_TICKET";
export const GET_USER_TICKETS = "GET_USER_TICKETS";
export const GET_USER_TICKETS_LIVING = "GET_USER_TICKETS_LIVING";
export const GET_USER_TICKETS_PARKING = "GET_USER_TICKETS_PARKING";
export const GET_USER_TICKETS_WAREHOUSE = "GET_USER_TICKETS_WAREHOUSE";

export const GET_APARTMENTS = "GET_APARTMENTS";
export const GET_IDEAS_GEO = "GET_IDEAS_GEO";
export const GET_APARTMENTS_GEO = "GET_APARTMENTS_GEO";

export const GET_USER_PARKING_BUILDINGS = "GET_USER_PARKING_BUILDINGS";
export const GET_USER_PARKING_PLACES = "GET_USER_PARKING_PLACES";
export const GET_EMPLOYEE_TICKETS_LIVING = "GET_EMPLOYEE_TICKETS_LIVING";
export const REJECT_TICKET_LIVING = "REJECT_TICKET_LIVING";
export const APPROVE_TICKET_LIVING = "APPROVE_TICKET_LIVING";
export const GET_EMPLOYEE_TICKETS_PARKING = "GET_EMPLOYEE_TICKETS_PARKING";
export const REJECT_TICKET_PARKING = "REJECT_TICKET_PARKING";
export const APPROVE_TICKET_PARKING = "APPROVE_TICKET_PARKING";
export const SEND_CONTRACT_INFO_LIVING = "SEND_CONTRACT_INFO_LIVING";
export const GET_USER_TICKET_PARKING_PAYMENT_LINK = "GET_USER_TICKET_PARKING_PAYMENT_LINK";
export const UPDATE_TICKET_APARTMENT = "UPDATE_TICKET_APARTMENT";
export const UPDATE_TICKET_APARTMENT_VIEWED = "UPDATE_TICKET_APARTMENT_VIEWED";
export const SEND_CONTRACT_INFO_PARKING = "SEND_CONTRACT_INFO_PARKING";
export const GET_EMPLOYEE_TICKETS_WAREHOUSE = "GET_EMPLOYEE_TICKETS_WAREHOUSE";
export const REJECT_TICKET_WAREHOUSE = "REJECT_TICKET_WAREHOUSE";
export const APPROVE_TICKET_WAREHOUSE = "APPROVE_TICKET_WAREHOUSE";
export const SEND_CONTRACT_INFO_WAREHOUSE = "SEND_CONTRACT_INFO_WAREHOUSE";
export const GET_WAREHOUSE_PAYMENT_LINK = "GET_WAREHOUSE_PAYMENT_LINK";

export const DELETE_USER_TICKET = "DELETE_USER_TICKET";
export const DELETE_USER_TICKET_LIVING = "DELETE_USER_TICKET_LIVING";
export const DELETE_USER_TICKET_PARKING = "DELETE_USER_TICKET_PARKING";
export const DELETE_USER_TICKET_WAREHOUSE = "DELETE_USER_TICKET_WAREHOUSE";

export const CREATE_USER_TICKET = "CREATE_USER_TICKET";
export const CREATE_USER_TICKET_LIVING = "CREATE_USER_TICKET_LIVING";
export const CREATE_LEGAL_TICKET_LIVING = "CREATE_LEGAL_TICKET_LIVING";
export const CREATE_USER_TICKET_PARKING = "CREATE_USER_TICKET_PARKING";
export const CREATE_USER_TICKET_WAREHOUSE = "CREATE_USER_TICKET_WAREHOUSE";

export const ADD_USER_TICKET_FILE = "ADD_USER_TICKET_FILE";
export const ADD_USER_TICKET_FILE_LIVING = "ADD_USER_TICKET_FILE_LIVING";
export const ADD_USER_TICKET_NEIGHBOR = "ADD_USER_TICKET_NEIGHBOR";
export const REQUEST_APPROVAL_LIVING = "REQUEST_APPROVAL_LIVING";
export const ADD_USER_TICKET_FILE_PARKING = "ADD_USER_TICKET_FILE_PARKING";
export const ADD_USER_TICKET_FILE_WAREHOUSE = "ADD_USER_TICKET_FILE_WAREHOUSE";
export const ADD_WAREHOUSE_FILES = "ADD_WAREHOUSE_FILES";
export const ADD_PARKING_FILES = "ADD_PARKING_FILES";

export const REGISTER_EMPLOYEE = "REGISTER_EMPLOYEE";
export const ACCOUNT_BLOCK = "ACCOUNT_BLOCK";
export const ACCOUNT_UNBLOCK = "ACCOUNT_UNBLOCK";
export const ACCOUNT_SET_ROLES = "ACCOUNT_SET_ROLES";
export const ACCOUNT_LOGOUT = "ACCOUNT_LOGOUT";
export const USER_LOGIN = "USER_LOGIN";
export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const ACCOUNT_CREATE = "ACCOUNT_CREATE";
export const GET_ACCOUNT = "GET_ACCOUNT";
export const ACCESS_TOKEN_COOKIE = "access_token";
export const REFRESH_ACCESS_TOKEN_COOKIE = "refresh_token";
export const GET_ACCESS_TOKEN = "GET_ACCESS_TOKEN";
export const SET_OAUTH_TOKENS = "SET_OAUTH_TOKENS";
export const FETCH_ACCESS_TOKEN = "FETCH_ACCESS_TOKEN";
export const CREATE_USER_VEHICLE = "CREATE_USER_VEHICLE";
export const UPDATE_USER_VEHICLE = "UPDATE_USER_VEHICLE";
export const STORE_USER_VEHICLES = "STORE_USER_VEHICLES";
export const CREATE_VEHICLE_DOCUMENT = "CREATE_VEHICLE_DOCUMENT";
export const DELETE_VEHICLE_DOCUMENT = "DELETE_VEHICLE_DOCUMENT";
export const UPDATE_VEHICLE_DOCUMENTS = "UPDATE_VEHICLE_DOCUMENTS";
export const DELETE_USER_VEHICLE = "DELETE_USER_VEHICLE";
export const CREATE_USER_NEIGHBOR = "CREATE_USER_NEIGHBOR";
export const UPDATE_USER_NEIGHBOR = "UPDATE_USER_NEIGHBOR";
export const DELETE_USER_NEIGHBOR = "DELETE_USER_NEIGHBOR";
export const CREATE_NEIGHBOR_DOCUMENT = "CREATE_NEIGHBOR_DOCUMENT";
export const DELETE_NEIGHBOR_DOCUMENT = "DELETE_NEIGHBOR_DOCUMENT";
export const UPDATE_NEIGHBOR_DOCUMENTS = "UPDATE_NEIGHBOR_DOCUMENTS";
export const STORE_USER_NEIGHBORS = "STORE_USER_NEIGHBORS";
export const CREATE_USER_DOCUMENT = "CREATE_USER_DOCUMENT";
export const DELETE_USER_DOCUMENT = "DELETE_USER_DOCUMENT";
export const GET_USER_DOCUMENTS = "GET_USER_DOCUMENTS";
export const STORE_USER_DOCUMENTS = "STORE_USER_DOCUMENTS";
export const UPDATE_USER_DOCUMENTS = "UPDATE_USER_DOCUMENTS";
export const GET_REFERENCES = "GET_REFERENCES";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const GET_USER_PROFILE_DEFAULT = "GET_USER_PROFILE_DEFAULT";
export const CHANGE_USER_PROFILE_PASSWORD = "CHANGE_USER_PROFILE_PASSWORD";
export const CHANGE_USER_PROFILE_EMAIL = "CHANGE_USER_PROFILE_EMAIL";
export const UPDATE_USER_PROFILE_AVATAR = "UPDATE_USER_PROFILE_AVATAR";

export const GET_COMPANY = "GET_COMPANY";
export const UPDATE_COMPANY_PROFILE = "UPDATE_COMPANY_PROFILE";
export const UPDATE_COMPANY_LOGO = "UPDATE_COMPANY_LOGO";
export const UPDATE_COMPANY_CARD = "UPDATE_COMPANY_CARD";
export const UPDATE_COMPANY_BANK = "UPDATE_COMPANY_BANK";

export const GET_DATA = "GET_DATA";
export const GET_PAYMENT_LINK = "GET_PAYMENT_LINK";

export const GET_VACANCY_REFERENCES = "GET_VACANCY_REFERENCES";

export const GET_USER_VACANCY = "GET_USER_VACANCY";
export const FETCH_USER_VACANCY_BY_ID = "FETCH_USER_VACANCY_BY_ID";

export const CREATE_VACANCY = "CREATE_VACANCY";
export const UPDATE_VACANCY = "UPDATE_VACANCY";
export const CLOSE_VACANCY = "CLOSE_VACANCY";
export const PUBLISH_VACANCY = "PUBLISH_VACANCY";
export const REJECT_VACANCY = "REJECT_VACANCY";
export const EXPORT_USER_VACANCIES = "EXPORT_USER_VACANCIES";

export const SEARCH_VACANCY = "SEARCH_VACANCY";
export const FETCH_VACANCY = "FETCH_VACANCY";
export const RESPOND_VACANCY = "RESPOND_VACANCY";

export const GET_USER_TICKETS_CROWDFUNDING = "GET_USER_TICKETS_CROWDFUNDING";
export const GET_EMPLOYEE_TICKETS_CROWDFUNDING = "GET_EMPLOYEE_TICKETS_CROWDFUNDING";
export const REJECT_TICKET_CROWDFUNDING = "REJECT_TICKET_CROWDFUNDING";
export const APPROVE_TICKET_CROWDFUNDING = "APPROVE_TICKET_CROWDFUNDING";
export const DELETE_USER_TICKET_CROWDFUNDING = "DELETE_USER_TICKET_CROWDFUNDING";
