export const GET_PARKING_GEO = "GET_PARKING_GEO";

export const GET_USER_TICKETS = "GET_USER_TICKETS";
export const GET_USER_TICKETS_LIVING = "GET_USER_TICKETS_LIVING";
export const GET_USER_TICKETS_PARKING = "GET_USER_TICKETS_PARKING";

export const GET_USER_PARKING_BUILDINGS = "GET_USER_PARKING_BUILDINGS";
export const GET_USER_PARKING_PLACES = "GET_USER_PARKING_PLACES";

export const DELETE_USER_TICKET = "DELETE_USER_TICKET";
export const DELETE_USER_TICKET_LIVING = "DELETE_USER_TICKET_LIVING";
export const DELETE_USER_TICKET_PARKING = "DELETE_USER_TICKET_PARKING";

export const CREATE_USER_TICKET = "CREATE_USER_TICKET";
export const CREATE_USER_TICKET_LIVING = "CREATE_USER_TICKET_LIVING";
export const CREATE_USER_TICKET_PARKING = "CREATE_USER_TICKET_PARKING";
export const CREATE_USER_TICKET_WAREHOUSE = "CREATE_USER_TICKET_WAREHOUSE";


export const ADD_USER_TICKET_FILE = "ADD_USER_TICKET_FILE";
export const ADD_USER_TICKET_FILE_LIVING = "ADD_USER_TICKET_FILE_LIVING";
export const REQUEST_APPROVAL_LIVING = "REQUEST_APPROVAL_LIVING";
export const ADD_USER_TICKET_FILE_PARKING = "ADD_USER_TICKET_FILE_PARKING";
export const ADD_USER_TICKET_FILE_WAREHOUSE = "ADD_USER_TICKET_FILE_WAREHOUSE";
export const ADD_WAREHOUSE_FILES = "ADD_WAREHOUSE_FILES";

export const USER_LOGIN = "USER_LOGIN";
export const ACCOUNT_LOGIN = "ACCOUNT_LOGIN";
export const ACCOUNT_CREATE = "ACCOUNT_CREATE";
export const GET_ACCOUNT = "GET_ACCOUNT";
export const ACCESS_TOKEN_COOKIE = "access_token";
export const REFRESH_ACCESS_TOKEN_COOKIE = "refresh_token";
export const FETCH_ACCESS_TOKEN = "FETCH_ACCESS_TOKEN";
export const CREATE_USER_VEHICLE = "CREATE_USER_VEHICLE";
export const UPDATE_USER_VEHICLE = "UPDATE_USER_VEHICLE";
export const STORE_USER_VEHICLES = "STORE_USER_VEHICLES";
export const CREATE_VEHICLE_DOCUMENT = "CREATE_VEHICLE_DOCUMENT";
export const DELETE_VEHICLE_DOCUMENT = "DELETE_VEHICLE_DOCUMENT";
export const UPDATE_VEHICLE_DOCUMENTS = "UPDATE_VEHICLE_DOCUMENTS";
export const DELETE_USER_VEHICLE = "DELETE_USER_VEHICLE";
export const CREATE_USER_NEIGHBOR = "CREATE_USER_NEIGHBOR";
export const UPDATE_USER_NEIGHBOR = "UPDATE_USER_NEIGHBOR";
export const DELETE_USER_NEIGHBOR = "DELETE_USER_NEIGHBOR";
export const CREATE_NEIGHBOR_DOCUMENT = "CREATE_NEIGHBOR_DOCUMENT";
export const DELETE_NEIGHBOR_DOCUMENT = "DELETE_NEIGHBOR_DOCUMENT";
export const UPDATE_NEIGHBOR_DOCUMENTS = "UPDATE_NEIGHBOR_DOCUMENTS";
export const STORE_USER_NEIGHBORS = "STORE_USER_NEIGHBORS";
export const CREATE_USER_DOCUMENT = "CREATE_USER_DOCUMENT";
export const DELETE_USER_DOCUMENT = "DELETE_USER_DOCUMENT";
export const GET_USER_DOCUMENTS = "GET_USER_DOCUMENTS";
export const STORE_USER_DOCUMENTS = "STORE_USER_DOCUMENTS";
export const UPDATE_USER_DOCUMENTS = "UPDATE_USER_DOCUMENTS";
export const GET_REFERENCES = "GET_REFERENCES";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const GET_USER_PROFILE_DEFAULT = "GET_USER_PROFILE_DEFAULT";
export const CHANGE_USER_PROFILE_PASSWORD = "CHANGE_USER_PROFILE_PASSWORD";
export const CHANGE_USER_PROFILE_EMAIL = "CHANGE_USER_PROFILE_EMAIL";
export const UPDATE_USER_PROFILE_AVATAR = "UPDATE_USER_PROFILE_AVATAR";

export const GET_COMPANY = "GET_COMPANY";
export const UPDATE_COMPANY_PROFILE = "UPDATE_COMPANY_PROFILE";
export const UPDATE_COMPANY_LOGO = "UPDATE_COMPANY_LOGO";
export const UPDATE_COMPANY_CARD = "UPDATE_COMPANY_CARD";
export const UPDATE_COMPANY_BANK = "UPDATE_COMPANY_BANK";


