export const SET_USER_TICKET = "SET_USER_TICKET";
export const SET_USER_TICKETS = "SET_USER_TICKETS";

export const SET_CREATE_TICKET = "SET_CREATE_TICKET";

export const SET_DESIGN_SECTIONS = "SET_DESIGN_SECTIONS";
export const SET_DESIGN_SECTION = "SET_DESIGN_SECTION";

export const SET_PROFILE_FORM_FIRSTNAME = "SET_PROFILE_FORM_FIRSTNAME";
export const SET_PROFILE_FORM_LASTNAME = "SET_PROFILE_FORM_LASTNAME";
export const SET_PROFILE_FORM_PATRONYMIC = "SET_PROFILE_FORM_PATRONYMIC";
export const SET_PROFILE_FORM_NO_PATRONYMIC = "SET_PROFILE_FORM_NO_PATRONYMIC";
export const SET_PROFILE_FORM_EMAIL = "SET_PROFILE_FORM_EMAIL";
export const SET_PROFILE_FORM_PHONE = "SET_PROFILE_FORM_PHONE";
export const SET_PROFILE_FORM_TELEGRAM_ALIAS = "SET_PROFILE_FORM_TELEGRAM_ALIAS";
export const SET_PROFILE_FORM_NEW_EMAIL = "SET_PROFILE_FORM_NEW_EMAIL";
export const SET_PROFILE_FORM_AVATAR_URL = "SET_PROFILE_FORM_AVATAR_URL";

export const SET_NEW_PASSWORD_FORM_OLD_PASSWORD = "SET_NEW_PASSWORD_FORM_OLD_PASSWORD";
export const SET_NEW_PASSWORD_FORM_PASSWORD = "SET_NEW_PASSWORD_FORM_PASSWORD";
export const SET_NEW_PASSWORD_FORM_CONFIRM_PASSWORD = "SET_NEW_PASSWORD_FORM_CONFIRM_PASSWORD";

export const SET_GEODATA = "SET_GEODATA";
export const SET_FEATURE_ID = "SET_FEATURE_ID";
export const SET_POINT_COORDS = "SET_POINT_COORDS";
export const SET_DRAW_TYPE = "SET_DRAW_TYPE";
export const SET_CESIUM = "SET_CESIUM";
export const SET_CLUSTERING = "SET_CLUSTERING";
export const SET_MAP_ENTITY_DISTANCE = "SET_MAP_ENTITY_DISTANCE";
export const SET_USER = "SET_USER";
export const SET_EMPTY = "SET_EMPTY";
export const SET_INSTANCE = "SET_INSTANCE";
export const SET_DATA = "SET_DATA";
export const SET_QUERY = "SET_QUERY";
export const UPDATE_DATA = "UPDATE_DATA";
export const SET_CURRENT = "SET_CURRENT";
export const SET_DETAILS = "SET_DETAILS";
export const SET_DETAILS_EMPTY = "SET_DETAILS_EMPTY";
export const SET_FILTERS = "SET_FILTERS";
export const SET_TICKET_ID = "SET_TICKET_ID";
export const SET_PAID = "SET_PAID";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_PASSPORT = "SET_PASSPORT";
export const SET_INN = "SET_INN";
export const SET_SNILS = "SET_SNILS";
export const SET_DOCUMENTS = "SET_DOCUMENTS";
export const SET_JOB = "SET_JOB";
export const SET_VEHICLE_ITEM = "SET_VEHICLE_ITEM";
export const UPDATE_VEHICLES = "UPDATE_VEHICLES";
export const CREATE_VEHICLE_ITEM = "CREATE_VEHICLE_ITEM";
export const SET_ITEMS = "SET_ITEMS";
export const SET_STATE = "SET_STATE";
export const SET_DELETED_ID = "SET_DELETED_ID";
export const CLEAR_DELETED_IDS = "CLEAR_DELETED_IDS";
export const SET_STATE_DEFAULT = "SET_STATE_DEFAULT";

export const SET_REFERENCES = "SET_REFERENCES";

export const SET_COMPANY_PROFILE = "SET_COMPANY_PROFILE";
export const SET_COMPANY_CARD = "SET_COMPANY_CARD";
export const SET_COMPANY_BANK = "SET_COMPANY_BANK";
export const SET_COMPANY_LOGO = "SET_COMPANY_LOGO";
export const SET_COMPANY_ID = "SET_COMPANY_ID";
export const SET_COMPANY_VERIFY_REQUEST = "SET_COMPANY_VERIFY_REQUEST";

export const SET_PARKING_PLACES = "SET_PARKING_PLACES";
export const SET_PARKING_PLACE = "SET_PARKING_PLACE";
export const SET_PARKING_INFO = "SET_PARKING_INFO";

export const UPDATE_FILTERS = "UPDATE_FILTERS";
export const UPDATE_PAGINATION = "UPDATE_PAGINATION";
export const UPDATE_APARTMENTS_PAGINATION = "UPDATE_APARTMENTS_PAGINATION";

export const SET_USER_VACANCIES = "SET_USER_VACANCIES";
export const SET_USER_VACANCY = "SET_USER_VACANCY";

export const SET_VACANCY_REFERENCES = "SET_VACANCY_REFERENCES";
export const SET_SEARCH_VACANCY_ERROR = "SET_SEARCH_VACANCY_ERROR";
export const SET_VACANCIES = "SET_VACANCIES";
export const SET_VACANCY = "SET_VACANCY";
export const SET_VACANCY_CANDIDATES = "SET_VACANCY_CANDIDATES";
export const SET_CANDIDATE_VIEWED = "SET_CANDIDATE_VIEWED";
export const REFRESH_VACANCY_CANDIDATE = "REFRESH_VACANCY_CANDIDATE";

export const UPDATE_USER_VACANCY_PAGINATION = "UPDATE_USER_VACANCY_PAGINATION";
export const UPDATE_USER_VACANCY_CANDIDATES_PAGINATION = "UPDATE_USER_VACANCY_CANDIDATES_PAGINATION";

export const UPDATE_EMPLOYEE_RESPONDS_PAGINATION = "UPDATE_EMPLOYEE_RESPONDS_PAGINATION";
export const SET_EMPLOYEE_RESPONDS = "SET_EMPLOYEE_RESPONDS";

export const UPDATE_VERIFICATION_REQUESTS_PAGINATION = "UPDATE_VERIFICATION_REQUESTS_PAGINATION";
export const SET_VERIFICATION_REQUESTS = "SET_VERIFICATION_REQUESTS";
export const SET_VERIFICATION_REQUESTS_REFERENCES = "SET_VERIFICATION_REQUESTS_REFERENCES";

export const SET_TREES_STATS = "SET_TREES_STATS";
export const SET_LIGHT_STATS = "SET_LIGHT_STATS";
export const SET_TREE = "SET_TREE";
export const SET_LIGHT = "SET_LIGHT";
export const SET_COMMERCE_PLACE = "SET_COMMERCE_PLACE";

export const SET_TOURISM_MENU = "SET_TOURISM_MENU";
export const SET_LAYER_GEOJSON = "SET_LAYER_GEOJSON";
export const SET_TOURISM_ENTITY = "SET_TOURISM_ENTITY";
export const SET_TOURISM_CURRENT_LAYER = "SET_TOURISM_CURRENT_LAYER";

export const SET_BUILDINGS_MENU = "SET_BUILDINGS_MENU";
export const SET_BUILDINGS_GEOJSON = "SET_BUILDINGS_GEOJSON";
export const SET_BUILDINGS_MAP_BUILDING = "SET_BUILDINGS_MAP_BUILDING";

export const SET_SECURITY_MENU = "SET_SECURITY_MENU";
export const SET_SECURITY_GEOJSON = "SET_SECURITY_GEOJSON";
export const SET_SECURITY_LAYERS_VISIBILITY = "SET_SECURITY_LAYERS_VISIBILITY";
