export const SET_USER_TICKETS = "SET_USER_TICKETS";

export const SET_PROFILE_FORM_FIRSTNAME = "SET_PROFILE_FORM_FIRSTNAME";
export const SET_PROFILE_FORM_LASTNAME = "SET_PROFILE_FORM_LASTNAME";
export const SET_PROFILE_FORM_PATRONYMIC = "SET_PROFILE_FORM_PATRONYMIC";
export const SET_PROFILE_FORM_EMAIL = "SET_PROFILE_FORM_EMAIL";
export const SET_PROFILE_FORM_PHONE = "SET_PROFILE_FORM_PHONE";
export const SET_PROFILE_FORM_TELEGRAM_ALIAS = "SET_PROFILE_FORM_TELEGRAM_ALIAS";
export const SET_PROFILE_FORM_NEW_EMAIL = "SET_PROFILE_FORM_NEW_EMAIL";
export const SET_PROFILE_FORM_AVATAR_URL = "SET_PROFILE_FORM_AVATAR_URL";

export const SET_NEW_PASSWORD_FORM_OLD_PASSWORD = "SET_NEW_PASSWORD_FORM_OLD_PASSWORD";
export const SET_NEW_PASSWORD_FORM_PASSWORD = "SET_NEW_PASSWORD_FORM_PASSWORD";
export const SET_NEW_PASSWORD_FORM_CONFIRM_PASSWORD = "SET_NEW_PASSWORD_FORM_CONFIRM_PASSWORD";

export const SET_USER = "SET_USER";
export const SET_EMPTY = "SET_EMPTY";
export const SET_ACCOUNT = "SET_ACCOUNT";
export const SET_ACCESS_TOKEN = "SET_ACCESS_TOKEN";
export const SET_REFRESH_TOKEN = "SET_REFRESH_TOKEN";
export const SET_PASSPORT = "SET_PASSPORT";
export const SET_INN = "SET_INN";
export const SET_SNILS = "SET_SNILS";
export const SET_JOB = "SET_JOB";
export const SET_VEHICLE_ITEM = "SET_VEHICLE_ITEM";
export const UPDATE_VEHICLES = "UPDATE_VEHICLES";
export const CREATE_VEHICLE_ITEM = "CREATE_VEHICLE_ITEM";
export const SET_ITEMS = "SET_ITEMS";
export const SET_STATE = "SET_STATE";
export const SET_DELETED_ID = "SET_DELETED_ID";
export const CLEAR_DELETED_IDS = "CLEAR_DELETED_IDS";
export const SET_STATE_DEFAULT = "SET_STATE_DEFAULT";
