export const SET_USER_TICKETS = "SET_USER_TICKETS";

export const SET_PROFILE_FORM_FIRSTNAME = "SET_PROFILE_FORM_FIRSTNAME";
export const SET_PROFILE_FORM_LASTNAME = "SET_PROFILE_FORM_LASTNAME";
export const SET_PROFILE_FORM_PATRONYMIC = "SET_PROFILE_FORM_PATRONYMIC";
export const SET_PROFILE_FORM_EMAIL = "SET_PROFILE_FORM_EMAIL";
export const SET_PROFILE_FORM_PHONE = "SET_PROFILE_FORM_PHONE";
export const SET_PROFILE_FORM_TELEGRAM_ALIAS = "SET_PROFILE_FORM_TELEGRAM_ALIAS";
export const SET_PROFILE_FORM_NEW_EMAIL = "SET_PROFILE_FORM_NEW_EMAIL";

export const SET_NEW_PASSWORD_FORM_PASSWORD = "SET_NEW_PASSWORD_FORM_PASSWORD";
export const SET_NEW_PASSWORD_FORM_NEW_PASSWORD = "SET_NEW_PASSWORD_FORM_NEW_PASSWORD";
export const SET_NEW_PASSWORD_FORM_CONFIRM_PASSWORD = "SET_NEW_PASSWORD_FORM_CONFIRM_PASSWORD";
